CREATE PROC FI_SP_IncBeneficiarioV1
    @CPF           VARCHAR (14) ,
	@NOME          VARCHAR (50),
	@IDCLIENTE     INT    
AS
BEGIN
	INSERT INTO BENEFICIARIOS (CPF, NOME, IDCLIENTE) 
	VALUES (@CPF, @NOME, @IDCLIENTE)

	SELECT SCOPE_IDENTITY()
END